# Site settings
title: vs.
description: |-
  poems
  by Sarah Quigley

author:
    name: Sarah Quigley
    first_name: Sarah
    surname: Quigley
email: sarah@sarahquigley.net

footer:
  organisation: a finite adventure
  organisation_link: 'http://finiteadventures.com'
  copyright_start: 2008


exclude: [Gemfile, Rakefile, Gemfile.lock, package.json, README.md, node_modules]

baseurl: ""
url: "http://poetry.sarahquigley.net"
excerpt_separator: "  "

sass:
  sass_dir: _styles

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-autoprefixer
  - jekyll-paginate

paginate: 13
