# Site settings
title: vs.
description: poems by Sarah Quigley

author:
    name: Sarah Quigley
    first_name: Sarah
    surname: Quigley
email: sarah@sarahquigley.net

exclude: [Gemfile, Rakefile, Gemfile.lock, package.json, README.md]

baseurl: "/poetry"
url: "http://sarahquigley.net"
excerpt_separator: "  "

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-autoprefixer
  - jekyll-paginate

paginate: 13
