# Site settings
title: Sarah writes poems 
description: "Poetry as it happens."

author:
    name: Sarah Quigley
    first_name: Sarah
    surname: Quigley
email: sarah@sarahquigley.net

baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty

# Sass
sass:
    sass_dir: _sass
    style: :compressed
